#!/bin/sh
ROCKY=rocky
if test "`uname -m`" = 'armv7l'; then
    # Cannot run Rocky on Raspberry Pi
    ROCKY=
fi

cd `dirname $0`
for os in buster bullseye $ROCKY; do
    for mta in postfix sendmail; do
        echo "RUNNING TESTS: $mta $os"
        ./run-regression-tests-on-docker $mta $os "$@"
    done
done
